[package]
name = "ontology-p2p"
version = "0.1.0"
authors = ["laizy <laizhichao@onchain.com>"]

[dependencies]
byteorder = "1.0"
bytes = "0.4"
tokio-io = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
